### PR TITLE
fix: retrieve only latest multiaddress

### LINKED ISSUE #309: Announced peers are not updated
# Description

After migrating Brazil VM and use different IP, the relayer and exit nodes are not working properly and a GnosisVPN connection cannot be established because they cannot ping each other.

The goal is to make a GnosisVPN connection against brazil:
````
[destinations.Brazil]
address = "0x12b78461da59e8317c61bd249ea0dea2aa9527de"
meta = { location = "São Paulo" }
path = { intermediates = [ "0x6250eb481b40f4609d32de35bd9b827212713f35" ] }
````

# Testing data

## Relayer Node Peers
````
➜  curl -s https://gnosisvpn-relayer-node-sao-paulo-01.staging.gnosisvpn.io/api/v4/node/peers -H "X-Auth-Token: $HOPRD_API_TOKEN" | jq -r '.announced[] | select(.address == "0x12b78461da59E8317C61bD249EA0DEA2aA9527de")'
{
  "address": "0x12b78461da59E8317C61bD249EA0DEA2aA9527de",
  "multiaddrs": [
    "/ip4/185.9.1.81/udp/9091/quic-v1",   <=== Incorret
    "/ip4/35.215.200.73/udp/9091/quic-v1", <=== Incorret
    "/ip4/185.9.1.82/udp/9091/quic-v1"
  ]
}
````
## Exit Node Peers
````
➜  curl -s https://gnosisvpn-exit-node-sao-paulo-01.staging.gnosisvpn.io/api/v4/node/peers -H "X-Auth-Token: $HOPRD_API_TOKEN" | jq -r '.announced[] | select(.address == "0x6250Eb481b40F4609d32DE35bD9b827212713f35")'
{
  "address": "0x6250Eb481b40F4609d32DE35bD9b827212713f35",
  "multiaddrs": [
    "/ip4/35.215.234.118/udp/9091/quic-v1",  <=== Incorret
    "/ip4/185.9.1.82/udp/9091/quic-v1", <=== Incorret
    "/ip4/35.215.200.73/udp/9091/quic-v1"
  ]
}
````
## Blokli inspector exit-node
````
➜  ./result/bin/blokli-inspector -u https://blokli.jura.hoprnet.link query account -a 0x12b78461da59e8317c61bd249ea0dea2aa9527de
[
  {
    "chain_key": "0x12b78461da59e8317c61bd249ea0dea2aa9527de",
    "keyid": 37,
    "multi_addresses": [
      "/ip4/185.9.1.81/udp/9091/quic-v1",
      "/ip4/35.215.200.73/udp/9091/quic-v1",
      "/ip4/185.9.1.82/udp/9091/quic-v1"
    ],
    "packet_key": "d4b02fd384a2a3f249f6e5e5cac5b5323b6c72fe790e98e7e25c2e83731f3cfb",
    "safe_address": "0xdc0dea7a62b02ce24cc8ce8dead861614d15c3c1"
  }
]
````

## Blokli inspector relayer-node
````
➜  ./result/bin/blokli-inspector -u https://blokli.jura.hoprnet.link query account -a 0x6250eb481b40f4609d32de35bd9b827212713f35
[
  {
    "chain_key": "0x6250eb481b40f4609d32de35bd9b827212713f35",
    "keyid": 31,
    "multi_addresses": [
      "/ip4/35.215.234.118/udp/9091/quic-v1",
      "/ip4/185.9.1.82/udp/9091/quic-v1",
      "/ip4/35.215.200.73/udp/9091/quic-v1"
    ],
    "packet_key": "4ae0c2d2ecf289cd1b5d483fd5ced3893bcf8f39f7981966424c6725ba004379",
    "safe_address": "0xdc0dea7a62b02ce24cc8ce8dead861614d15c3c1"
  }
]
````

## Ping from exit node

```bash
➜  curl -H "X-Auth-Token: $HOPRD_API_TOKEN" -X POST https://gnosisvpn-exit-node-sao-paulo-01.staging.gnosisvpn.io/api/v4/peers/0x6250eb481b40f4609d32de35bd9b827212713f35/ping
{"status":"TIMEOUT"}
```

## Ping from relayer node

```bash
➜  curl -H "X-Auth-Token: $HOPRD_API_TOKEN" -X POST https://gnosisvpn-relayer-node-sao-paulo-01.staging.gnosisvpn.io/api/v4/peers/0x12b78461da59e8317c61bd249ea0dea2aa9527de/ping
{"status":"TIMEOUT"}
```

# Expected behaviour

I would expect the announced peers to be filtered and get only the latest one

# Context info

| Node                                | Endpoint                                                         | Node Address                                 | Peer ID                                                | Public IP |
| ----------------------------------- | ---------------------------------------------------------------- | -------------------------------------------- | ------------------------------------------------------ | ------ |
| gnosisvpn-exit-node-sao-paulo-01    | https://gnosisvpn-exit-node-sao-paulo-01.staging.gnosisvpn.io    | `0x12b78461da59e8317c61bd249ea0dea2aa9527de` | `12D3KooWQ8cRPMHujqh44ESBpKDvix5qDJek1zs7kzDrsZRtUt7C` | 185.9.1.82 |
| gnosisvpn-relayer-node-sao-paulo-01 | https://gnosisvpn-relayer-node-sao-paulo-01.staging.gnosisvpn.io | `0x6250eb481b40f4609d32de35bd9b827212713f35` | `12D3KooWErf7p1g5ZpmBBUM8aaXEXAbiGJjkMGBdUjXoS7vtLzrL` | 35.215.200.73 |

### PR DESCRIPTION
**Pull request by jeandemeusy**
Returns only the latest multiaddress, as only this one should be valid. Any historical data is not necessary.

Data is still returned as a list, containing up to a single element, to not break the compatibility with the clients of blokli. Could be improved in the future.

Fixes #309

### CODE REVIEW

**Review by NumberFour8 — APPROVED** [review]
Version bump missing.

File: api/tests/account_api_integration_test.rs [hunk 1]
```diff
@@ -473,6 +473,68 @@ async fn test_accounts_query_with_multiaddresses() -> anyhow::Result<()> {
...
+    let chain_key = keypair.public().to_address();
+    let packet_key = offchain.public();
+
+    db.upsert_account(None, 1, chain_key, *packet_key, None, 100, 0, 0)
+        .await?;
+
+    let first_multiaddr_str = "/ip4/127.0.0.1/tcp/9091";
+    let second_multiaddr_str = "/ip4/127.0.0.1/tcp/9092";
+    let first_multiaddr: Multiaddr = first_multiaddr_str.parse().unwrap();
+    let second_multiaddr: Multiaddr = second_multiaddr_str.parse().unwrap();
```
Comment (Teebor-Choka) [inline api/tests/account_api_integration_test.rs]:
```suggestion
    let first_multiaddr: Multiaddr = first_multiaddr_str.parse().context("must be able to parse multiaddr")?;
    let second_multiaddr: Multiaddr = second_multiaddr_str.parse().context("must be able to parse multiaddr")?;
```

File: api/tests/account_api_integration_test.rs [hunk 2]
```diff
@@ -473,6 +473,68 @@ async fn test_accounts_query_with_multiaddresses() -> anyhow::Result<()> {
...
+    "#;
+
+    let response = execute_graphql_query(&schema, query).await;
+    assert!(response.errors.is_empty());
+
+    let data = response.data.into_json()?;
+    let accounts = extract_accounts_from_result(&data)?;
+    assert_eq!(accounts.len(), 1);
+
+    let multi_addresses = accounts[0]["multiAddresses"].as_array().unwrap();
```
Comment (Teebor-Choka) [inline api/tests/account_api_integration_test.rs]:
```suggestion
    let multi_addresses = accounts[0]["multiAddresses"].as_array().context("should be available");
```

File: api/tests/account_api_integration_test.rs [hunk 3]
```diff
@@ -473,6 +473,68 @@ async fn test_accounts_query_with_multiaddresses() -> anyhow::Result<()> {
...
+    assert_eq!(multi_addresses.len(), 1);
+    assert_eq!(multi_addresses[0].as_str().unwrap(), second_multiaddr_str);
```
Comment (Teebor-Choka) [inline api/tests/account_api_integration_test.rs]:
```suggestion
    assert_eq!(&received_multiaddrs, &[second_multiaddr]);
```

File: api/tests/account_api_integration_test.rs (hunk 2 above)
Comment (Teebor-Choka) [inline api/tests/account_api_integration_test.rs]:
```suggestion
    let received_multiaddrs = accounts[0]["multiAddresses"].as_array().unwrap();
```

File: api/tests/account_subscription_test.rs [hunk 4]
```diff
@@ -745,7 +745,7 @@ async fn test_account_subscription_handles_account_with_multiple_announcements()
     let multiaddr1: Multiaddr = "/ip4/127.0.0.1/tcp/9091".parse().unwrap();
     let multiaddr2: Multiaddr = "/ip4/127.0.0.1/tcp/9092".parse().unwrap();
     db.insert_announcement(None, chain_key, multiaddr1, 101).await.unwrap();
-    db.insert_announcement(None, chain_key, multiaddr2, 102).await.unwrap();
+    db.insert_announcement(None, chain_key, multiaddr2.clone(), 102).await.unwrap();
```
Comment (Teebor-Choka) [inline api/tests/account_subscription_test.rs]:
```suggestion
    db.insert_announcement(None, chain_key, *multiaddr2, 102).await.context("should be able to insert a multiaddress");
```

File: api/tests/account_api_integration_test.rs (hunk 3 above)
Comment (jeandemeusy) [reply api/tests/account_api_integration_test.rs]: It can't work simply like this, as the first object is a vector of JsonValues, not a vector of string
